### ISSUE TITLE
加载图像批次有问题

### ISSUE THREAD

**Issue by 59420203** [EvilBT/ComfyUI_SLK_joy_caption_two#10]
图片在用于批量标注节点时存在问题，似乎导致了提示词类型的出错，有时打标单词，有时打标很短的自然语言，并且人名与自定义提示词的功能也失效了。
![捕获](https://github.com/user-attachments/assets/22fdc47d-67f2-4cfa-92b6-69c98dfea7a6)

**Comment by EvilBT** [comment]
> 图片在用于批量标注节点时存在问题，似乎导致了提示词类型的出错，有时打标单词，有时打标很短的自然语言，并且人名与自定义提示词的功能也失效了。 ![捕获](https://private-user-images.githubusercontent.com/49418811/376149392-22fdc47d-67f2-4cfa-92b6-69c98dfea7a6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjY1NDIsIm5iZiI6MTcyODkyNjI0MiwicGF0aCI6Ii80OTQxODgxMS8zNzYxNDkzOTItMjJmZGM0N2QtNjdmMi00Y2ZhLTkyYjYtNjljOThkZmVhN2E2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE3MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5Y2VkYzhjM2Y3MTBkOGFjYjE3MjQxZTA5OTFmYTQ0ZWQ4Njg1ZTcwNDFiNDMyM2E5NjZjMDc2YjMzNjU2ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mDt6txdzLeKKAUXucwZzFnWJqiMlcs8bhhQthxHkUuU)

自定义引导词是替换掉了你对这个大语言模型的对话内容的，本来你这张图大概是这个意思：请说出这张图片的详细信息，如果有人名，请用 babata 称呼他，之类的，你填上了那个自定义引导词之后，就变成你发了张图片给这个大模型，然后说：babata，它就不知道 你要干嘛了，一般不需要填自定义引导词，那些不是附加，而是直接替换掉预设值了
