### ISSUE TITLE
附加选项如何自定义？

### ISSUE THREAD

**Issue by mimimi13589** [EvilBT/ComfyUI_SLK_joy_caption_two#107]
我尝试着更改了文件，但是发现并没有生效，不知道为什么。是否支持自定义附加选项？我应该怎么做？

**Comment by EvilBT** [comment]
> 我尝试着更改了文件，但是发现并没有生效，不知道为什么。是否支持自定义附加选项？我应该怎么做？

作者本身只训练了那些附加选项，你用自定义的没意义，在高级里的那个自定义prompt就是自己的定义的提问，但是效果一般

**Comment by mimimi13589** [comment]
> > 我尝试着更改了文件，但是发现并没有生效，不知道为什么。是否支持自定义附加选项？我应该怎么做？
> 
> 作者本身只训练了那些附加选项，你用自定义的没意义，在高级里的那个自定义prompt就是自己的定义的提问，但是效果一般

是的，我用自定义prompt试了，感觉基本没什么影响，和我写的可以说驴唇不对马嘴。
