### ISSUE TITLE
求助,打标报错

### ISSUE THREAD

**Issue by VJleoliu2023** [EvilBT/ComfyUI_SLK_joy_caption_two#11]
Cannot handle this data type: (1, 1, 1280, 3), |u1

批量打标,不知道这么链对不对,麻烦佬看下

![image](https://github.com/user-attachments/assets/8acaa421-c442-45cf-9797-a1723643e5bb)
![image](https://github.com/user-attachments/assets/fea03757-22c3-4f67-b8b2-9b090325ce29)

**Comment by VJleoliu2023** [comment]
User specified an unsupported autocast device_type 'cuda:0'

换了一个图像路径的node,又有新的报错,哎^

![image](https://github.com/user-attachments/assets/f51dad79-fd40-4ffe-b677-e8e2309d0af7)
![image](https://github.com/user-attachments/assets/4af32fa3-6d92-49c8-9f82-4f6abbc8e3ef)

**Comment by VJleoliu2023** [comment]
是啊,我看到隔壁CXH_joy_caption也有类似'cuda:0'的报错,改了一行代码就好了,但是SLK_joy_caption_two不可以,还望佬帮忙解决一下.

**Comment by EvilBT** [comment]
> 是啊,我看到隔壁CXH_joy_caption也有类似'cuda:0'的报错,改了一行代码就好了,但是SLK_joy_caption_two不可以,还望佬帮忙解决一下.

你自己先测试一下，把：device_type = str(joy_two_pipeline.load_device)
        with torch.amp.autocast_mode.autocast(device_type, enabled=True):，这个改成
        with torch.amp.autocast_mode.autocast('cuda', enabled=True):

**Comment by EvilBT** [comment]
更新一下看看
