### ISSUE TITLE
RGBA pic error

### ISSUE THREAD

**Issue by xiongbb** [EvilBT/ComfyUI_SLK_joy_caption_two#13]
4个通道的训练集图片报错

Error processing 0027.jpg :Given groups=1, weight of size [1152, 3, 14, 14], expected input[1, 4, 384, 384] to have 3 channels, but got 4 channels instead

希望能加上把RGBA处理成RGB，我自己写了个脚本先处理了
```python
from PIL import Image
import os

input_folder = './'  
output_folder = './fixed'  


if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for file_name in os.listdir(input_folder):
    if file_name.endswith(('.jpg', '.jpeg', '.png')):
        file_path = os.path.join(input_folder, file_name)
        img = Image.open(file_path)
        if img.mode == 'RGBA':
            img = img.convert('RGB')        

        output_path = os.path.join(output_folder, file_name)
        img.save(output_path, quality=100)

```

**Comment by EvilBT** [comment]
> 4个通道的训练集图片报错
> 
> Error processing 0027.jpg :Given groups=1, weight of size [1152, 3, 14, 14], expected input[1, 4, 384, 384] to have 3 channels, but got 4 channels instead
> 
> 希望能加上把RGBA处理成RGB，我自己写了个脚本先处理了
> 
> ```python
> from PIL import Image
> import os
> 
> input_folder = './'  
> output_folder = './fixed'  
> 
> 
> if not os.path.exists(output_folder):
>     os.makedirs(output_folder)
> 
> for file_name in os.listdir(input_folder):
>     if file_name.endswith(('.jpg', '.jpeg', '.png')):
>         file_path = os.path.join(input_folder, file_name)
>         img = Image.open(file_path)
>         if img.mode == 'RGBA':
>             img = img.convert('RGB')        
> 
>         output_path = os.path.join(output_folder, file_name)
>         img.save(output_path, quality=100)
> ```

已修复
