### ISSUE TITLE
能否支持最新的Llama-3.1-8B-Lexi-Uncensored-V2（CXH，葫芦大佬的layer插件也都支持该模型）

### ISSUE THREAD

**Issue by ousennke** [EvilBT/ComfyUI_SLK_joy_caption_two#17]
测试感觉Llama-3.1-8B-Lexi-Uncensored-V2打标适配范围最广（NSFW），也更加听话

**Comment by EvilBT** [comment]
> 测试感觉Llama-3.1-8B-Lexi-Uncensored-V2打标适配范围最广（NSFW），也更加听话

这次的模型大佬是在8B Instruct 下进行LORA训练的，你说的这个我看了一下：`该模型基于 Llama-3.1-8b-Instruct`, 应该也是可以的，你这个可以自行测试的，不需要改源码，你把项目根目录下的joy_config.json,最后的model字段添加这个模型就可以了：
{
  "model": [
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-8B-Instruct",
    "Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2"
  ]
}
然后重启就有这个选项了，会自动下载，同样的，可以手动下载，把文件放到 models/LLM/Llama-3.1-8B-Lexi-Uncensored-V2下，你帮我测试一下效果吧，我的8G显存测试这个一条要1个多小时

**Comment by EvilBT** [comment]
已添加，低显存可以用另外一个量化版本nf4
