### ISSUE TITLE
Error loading models: Unrecognized configuration class <class 'transformers.models.siglip.configuration_siglip.SiglipConfig'> for this kind of AutoModel: AutoModelForCausalLM.

### ISSUE THREAD

**Issue by masterliu2021** [EvilBT/ComfyUI_SLK_joy_caption_two#30]
请问这个是什么问题，要怎么解决呢

got prompt
Loading in NF4
Loading CLIP 📎
Loading VLM's custom vision model 📎
Loading tokenizer 🪙
Loading LLM: E:\PIC\Blender_ComfyUI.zip\ComfyUI-aki-v1.1\ComfyUI-aki-v1.1\models\LLM\Meta-Llama-3.1-8B-Instruct 🤖
Error loading models: Unrecognized configuration class <class 'transformers.models.siglip.configuration_siglip.SiglipConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by Windvale** [comment]
一样的问题

**Comment by hellloveyy** [comment]
我用bnb就不会报错
你试试 别的模型都有问题
