### ISSUE TITLE
只会使用Meta-Llama-3.1-8B-Instruct-bnb-4bit

### ISSUE THREAD

**Issue by zark119** [EvilBT/ComfyUI_SLK_joy_caption_two#34]
即使切换其他模型也只会导入这个模型

**Comment by EvilBT** [comment]
> 即使切换其他模型也只会导入这个模型

这是一个BUG，晚点修复一下，第一次加载成功之后切换新的模型代码没正确处理，所以目前默认是第一次点开始之后的选中的模型，我等会修复一下

**Comment by EvilBT** [comment]
已修复，可以更新一下
