### ISSUE TITLE
CLIPTextEncodeGeminiFlux not found

### ISSUE THREAD

**Issue by SanPy** [EvilBT/ComfyUI_SLK_joy_caption_two#35]
Excuse me, where can I find him

**Comment by EvilBT** [comment]
> Excuse me, where can I find him打扰一下，我在哪里可以找到他
You can replace it with a similar component. That is another node I wrote temporarily. It is not included in this node. You can remove it and select a node with similar functions.

**Comment by SanPy** [comment]
ok, thank yuo
