### ISSUE TITLE
高级批量中prefix_name的问题

### ISSUE THREAD

**Issue by lesteryebin** [EvilBT/ComfyUI_SLK_joy_caption_two#38]
prefix_name这个参数是否可以理解为触发词，我设置了这一项后反推出来的文本内并没有加入这个设置的字段，请作者复现一下，谢谢！

**Comment by lesteryebin** [comment]
测试了一下，prefix_name是重命名后的文件名前缀，可否在批量功能上增加一个触发词的字段设置，加在反推提示词前，谢谢

**Comment by EvilBT** [comment]
> 测试了一下，prefix_name是重命名后的文件名前缀，可否在批量功能上增加一个触发词的字段设置，加在反推提示词前，谢谢

已添加，更新一下
