### ISSUE TITLE
发现一个问题，与工作流连接会爆显存

### ISSUE THREAD

**Issue by crazyjtt03** [EvilBT/ComfyUI_SLK_joy_caption_two#43]
发现一个问题，单独运行不爆显存，但是一旦与工作流连接运行就爆显存，不管是接入图片或者输出文本都会，单独在一个框内不与工作流连接就不会爆显存。8G显存.

**Comment by EvilBT** [comment]
8G确实很勉强，这个本身就快6,7G了，你打开那个lowram，会稍微好一点，还是爆的话，就换成先批量生成，再批量读取会好一些，我也是8G的

**Comment by crazyjtt03** [comment]
好的，谢谢解答
