### ISSUE TITLE
看看这些问题？感谢

### ISSUE THREAD

**Issue by leoleelxh** [EvilBT/ComfyUI_SLK_joy_caption_two#58]
已经按照requirements的文件安装依赖，使用的是秋叶的启动器。
使用不同模型都不行，分别报如下图的错误，大佬看看：
![image](https://github.com/user-attachments/assets/2ede1bfb-801d-4195-a9ec-8769945b729f)
![image](https://github.com/user-attachments/assets/581696d2-16ae-462e-bb25-89c2afa5d17d)
![image](https://github.com/user-attachments/assets/98edfd6e-7d4d-45de-8129-910e005fddff)
![image](https://github.com/user-attachments/assets/68fbfd38-998c-49c2-bf17-e25ed5b71e5d)

**Comment by EvilBT** [comment]
秋叶启动器的话你看看是不是真的更新对了，这个提示peft的，明显就是peft的版本有问题，你已经确定模型都放对位置了，那就应该是peft还是没更新对

**Comment by leoleelxh** [comment]
> 秋叶启动器的话你看看是不是真的更新对了，这个提示peft的，明显就是peft的版本有问题，你已经确定模型都放对位置了，那就应该是peft还是没更新对

感谢，后来发现是torch和xformers的版本太高了，降级就可以了，🙏
