### ISSUE TITLE
8B反推的结果有问题

### ISSUE THREAD

**Issue by xiongbb** [EvilBT/ComfyUI_SLK_joy_caption_two#6]
同一张图，设置一样

8B反推结果经常不如8B-Instruct-bnb-4bit反推结果，8b的输出的提示词长度更短，还有一些设置偶尔不生效，比如{name}，水印输出等。

试了不少图，都这样。和hf上在线页面的输出结果相差甚远。测试显卡4090,示例的最简流程图。

**Comment by EvilBT** [comment]
> 同一张图，设置一样
> 
> 8B反推结果经常不如8B-Instruct-bnb-4bit反推结果，8b的输出的提示词长度更短，还有一些设置偶尔不生效，比如{name}，水印输出等。
> 
> 试了不少图，都这样。和hf上在线页面的输出结果相差甚远。测试显卡4090,示例的最简流程图。

检查了一下代码，是我的问题，他用的是Instruct版本训练的Lora的，我代码里写成了普通版本，你着急用的话，可以先到根目录下，把：joy_config.json里的 model那里添加多一个指定模型，并把原版的去掉：如下
`{
   "model": [
      "unsloth/Meta-Llama-3.1-8B-Instruct",
      "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"
  ]
}`
是我的疏忽了，因为我电脑只有8G，刚刚试用了这个8B的，用CPU跑了一个，也就4000秒才推理出来，但是是有效果的，你可以先自行修改一下，或者等我晚点更新一下代码

**Comment by EvilBT** [comment]
> 同一张图，设置一样
> 
> 8B反推结果经常不如8B-Instruct-bnb-4bit反推结果，8b的输出的提示词长度更短，还有一些设置偶尔不生效，比如{name}，水印输出等。
> 
> 试了不少图，都这样。和hf上在线页面的输出结果相差甚远。测试显卡4090,示例的最简流程图。

已经修复了，你更新一下代码即可
