### ISSUE TITLE
请问不显示结果是什么原因

### ISSUE THREAD

**Issue by zjs0813** [EvilBT/ComfyUI_SLK_joy_caption_two#66]
这里可以显示
<img width="888" alt="1731913939379" src="https://github.com/user-attachments/assets/ba92f180-64b7-4140-87ea-2f5ffd8d22a3">
结果没有输出
<img width="849" alt="1731914043800" src="https://github.com/user-attachments/assets/3ac4d5bd-c048-49bc-a830-e9d93e9bd7d7">

**Comment by EvilBT** [comment]
你这个不是我的节点，是LayerStyle的，看日志是有结果的，你试下直接当成prompt跑一下看看能不能出来类似的图片
