### ISSUE TITLE
Have you considered adding the InternVL model? It is similar to GPT-4o.

### ISSUE THREAD

**Issue by momoGBG** [EvilBT/ComfyUI_SLK_joy_caption_two#70]
![image](https://github.com/user-attachments/assets/2df0f031-57cd-4d3f-90d1-cc7dc7c59bbc)

**Comment by momoGBG** [comment]
https://huggingface.co/OpenGVLab/InternVL2-8B-MPO

**Comment by EvilBT** [comment]
I have tried it, it can only run under transformers==4.37.2, and my project must transformers>=4.44.0, the two are conflicting，Unresolvable version conflicts

**Comment by momoGBG** [comment]
> I have tried it, it can only run under transformers==4.37.2, and my project must transformers>=4.44.0, the two are conflicting，Unresolvable version conflicts

Alright, I guess it's because it's still based on the previous version of LLaMA 3 with some modifications, so they fixed the version. But thanks for trying anyway!
