### ISSUE TITLE
我把模型文件夹单独放到别的硬盘后映射路径，就会读取不到，还是在comfyui下的路径找

### ISSUE THREAD

**Issue by koori1945** [EvilBT/ComfyUI_SLK_joy_caption_two#80]
我把模型文件夹单独放到别的硬盘后映射路径，就会读取不到，还是在comfyui下的路径找，想问下怎么改模型读取路径

**Comment by EvilBT** [comment]
> 我把模型文件夹单独放到别的硬盘后映射路径，就会读取不到，还是在comfyui下的路径找，想问下怎么改模型读取路径

手动修改一下源码对应的路径那些，目前就是固定在models相关目录下的，你可以直接写死成你自己的本地文件夹

**Comment by koori1945** [comment]
我找到方法了，跟ai助手聊了半小时，因为我真的是一点程序都不懂，根目录下有个文件folder_paths.py里面有一句models_dir = os.path.join(base_path, "models")把等号后面修改成本地文件路径就行了，但是我发现每次跟新版本这个文件就会被重新下，我每次更新完版本都要改

**Comment by EvilBT** [comment]
> 我找到方法了，跟ai助手聊了半小时，因为我真的是一点程序都不懂，根目录下有个文件folder_paths.py里面有一句models_dir = os.path.join(base_path, "models")把等号后面修改成本地文件路径就行了，但是我发现每次跟新版本这个文件就会被重新下，我每次更新完版本都要改

你可以跟AI讲一下怎么克隆这个项目，然后直接基于你克隆的项目下载到custom目录下，你独立的node节点，可以稍微只改一下这个项目的名称，然后使用你自己的项目，就不会遇到更新版本就被重新下载的问题才对
